//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyInvite {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label nameLbl;
		
		protected System.Web.UI.WebControls.TextBox nameTxt;
		
		protected System.Web.UI.WebControls.Label rsvplbl;
		
		protected System.Web.UI.WebControls.DropDownList rsvpddl;
		
		protected System.Web.UI.WebControls.Button submitBtn;
	}
}
